#cloud-config
write_files:
- content: |
    CONDOR_HOST = manager.vgcn.usegalaxy.eu
    ALLOW_WRITE = 10.5.68.0/24, 10.19.0.0/16, 132.230.68.0/24, *.bi.uni-freiburg.de
    ALLOW_READ = $(ALLOW_WRITE)
    ALLOW_NEGOTIATOR = $(ALLOW_WRITE)
    DAEMON_LIST = COLLECTOR, MASTER, NEGOTIATOR, SCHEDD
    FILESYSTEM_DOMAIN = bi.uni-freiburg.de
    UID_DOMAIN = bi.uni-freiburg.de
    TRUST_UID_DOMAIN = True
    SOFT_UID_DOMAIN = True
  owner: root:root
  path: /etc/condor/condor_config.local
  permissions: '0644'
- content: |
    /data           /etc/auto.data          nfsvers=3
  owner: root:root
  path: /etc/auto.master.d/data.autofs
  permissions: '0644'
- content: |
    share  -rw,hard,intr,nosuid,quota  nfs.vgcn.usegalaxy.eu:/export/share
  owner: root:root
  path: /etc/auto.data
  permissions: '0644'
