#cloud-config
write_files:
- content: |
    CONDOR_HOST = manager.vgcn.usegalaxy.eu
    ALLOW_WRITE = 10.5.68.0/24, 10.19.0.0/16, 132.230.68.0/24, *.bi.uni-freiburg.de
    ALLOW_READ = $(ALLOW_WRITE)
    ALLOW_NEGOTIATOR = $(ALLOW_WRITE)
    DAEMON_LIST = COLLECTOR, MASTER, NEGOTIATOR, SCHEDD
    FILESYSTEM_DOMAIN = bi.uni-freiburg.de
    UID_DOMAIN = bi.uni-freiburg.de
    TRUST_UID_DOMAIN = True
    SOFT_UID_DOMAIN = True
  owner: root:root
  path: /etc/condor/condor_config.local
  permissions: '0644'
- content: |
    /data           /etc/auto.data          nfsvers=3
  owner: root:root
  path: /etc/auto.master.d/data.autofs
  permissions: '0644'
- content: |
    share  -rw,hard,intr,nosuid,quota  nfs.vgcn.usegalaxy.eu:/export/share
    0       -rw,hard,intr,nosuid,quota      sn01.bi.uni-freiburg.de:/export/data3/galaxy/net/data/&
    1       -rw,hard,intr,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
    2       -rw,hard,intr,nosuid,quota      sn01.bi.uni-freiburg.de:/export/data4/galaxy/net/data/&
    3       -rw,hard,intr,nosuid,quota      sn01.bi.uni-freiburg.de:/export/data5/galaxy/net/data/&
    4       -rw,hard,intr,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
    5       -rw,hard,intr,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
    6       -rw,hard,intr,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
    7       -rw,hard,intr,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
    dnb01   -rw,hard,intr,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    dnb02   -rw,hard,intr,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    dnb03   -rw,hard,intr,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    dnb04   -rw,hard,intr,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    db      -rw,hard,intr,nosuid,quota      sn02.bi.uni-freiburg.de:/export/fdata1/galaxy/net/data/&
  owner: root:root
  path: /etc/auto.data
  permissions: '0644'
#- content: |
    #conda_auto_init: true
    #conda_auto_install: true
    #managers:
        #_default_:
            #num_concurrent_jobs: 1
            #type: queued_python
    #message_queue_url: pyamqp://galaxy_test:7e8hWABdDNAGOiiyTa0lxEFft@proxy.usegalaxy.eu:5671//pulsar/galaxy_test?ssl=1
    #staging_directory: /scratch/
    #tool_dependency_dir: /usr/local/tools/
  #owner: pulsar:pulsar
  #path: /opt/pulsar/config/app.yml
  #permissions: '0640'

#runcmd:
 #- [ systemctl, enable, pulsar ]
 #- [ systemctl, start, pulsar ]
